# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "features/**", "feature/**", "fix/**", "hotfix/**", "docs/**", "doc/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Clean install project
      run: npm ci

    - name: Check ESlint
      run: npm run lint:es
    
    - name: Check markdown linting
      run: npm run lint:md

    - name: Run unit tests and check coverage
      run: npm test
      env:
        # Global
        NODE_ENV: ${{ vars.NODE_ENV }}
        PUBLIC_KEY: ${{ vars.PUBLIC_KEY }}
        # Auth Service
        PRIVATE_KEY_AUTH_SERVICE: ${{ secrets.PRIVATE_KEY_AUTH_SERVICE }}
        SECRET_CSURF_AUTH_SERVICE: ${{ secrets.SECRET_CSURF_AUTH_SERVICE }}
        DB_HOST_AUTH_SERVICE: ${{ vars.DB_HOST_AUTH_SERVICE }}
        DB_NAME_AUTH_SERVICE: ${{ vars.DB_NAME_AUTH_SERVICE }}
        DB_USER_AUTH_SERVICE: ${{ secrets.DB_USER_AUTH_SERVICE }}
        DB_PASS_AUTH_SERVICE: ${{ secrets.DB_PASS_AUTH_SERVICE }}
        DB_PORT_AUTH_SERVICE: ${{ vars.DB_PORT_AUTH_SERVICE }}
        PORT_AUTH_SERVICE: ${{ vars.PORT_AUTH_SERVICE }}
        # User Service
        DB_HOST_URM_SERVICE: ${{ vars.DB_HOST_URM_SERVICE }}
        DB_NAME_URM_SERVICE: ${{ vars.DB_NAME_URM_SERVICE }}
        DB_USER_URM_SERVICE: ${{ secrets.DB_USER_URM_SERVICE }}
        DB_PASS_URM_SERVICE: ${{ secrets.DB_PASS_URM_SERVICE }}
        DB_PORT_URM_SERVICE: ${{ vars.DB_PORT_URM_SERVICE }}
        PORT_URM_SERVICE: ${{ vars.PORT_URM_SERVICE }}
        
